### ISSUE TITLE
Version information?

### ISSUE THREAD

**Issue by austinbutler** [slorber/awesome-debounce-promise#11]
Is this project using semantic versioning? I ask because it was bumped to 2.x, but there's no changelog so not sure if there are breaking changes in it or not.

**Comment by slorber** [comment]
Hi

There are breaking changes as I une ported some internal functions and
rewrote everything in typescript, but if you did not have a fancy usage of
this lib you should be fine and if it's not I'll fix it

Le lun. 11 mars 2019 à 22:04, austinbutler <notifications@github.com> a
écrit :

**Comment by slorber** [comment]
@austinbutler is the upgrade ok or did you have any problem? I'm closing but feel free to reopen

**Comment by austinbutler** [comment]
I didn't try it yet due to the uncertainty but I will, and if I have problems I will open an issue. Thanks!

**Comment by slorber** [comment]
The default exported function did not change any behavior, only undocumented named exports were slighly changed

**Comment by austinbutler** [comment]
Yeah it seems to work as it did before.
