### ISSUE TITLE
How would I test the api call inside awesome-debounce-promise?

### ISSUE THREAD

**Issue by kurt-hardy** [slorber/awesome-debounce-promise#12]
Hi

Not really an issue but I'm wondering how I test this using jest.mock. (Im using react, jest and enzyme)

I have it setup like this:
`const searchApi = term => api.get(`search?searchTerm=${term}`);
const searchDebounce = AwesomeDebouncePromise(searchApi, 400);`

And then my `onChange` function is like:
` onSearch = (e) => {
        searchDebounce(e.target.value)
            .then((response) => {
                this.setState({
                    ....
                });
            })
    };`

Normally I would simulate the change and check that `api.get` is called with the search value but its just failing with `api.get` was never called.

My Test:
` it("should ", (done) => {
            const wrapper = shallow(<Search {...testProps} />);
            wrapper.find("Input").simulate("change", { target: { value: "searchTerm" } });
            setImmediate(() => {
                expect(api.get).toHaveBeenCalledTimes(1);
                done();
            });  
        });
`
Thanks
Kurtis

**Comment by slorber** [comment]
Hi,

Your code is a bit hard to read above.

You can probably do something like

```js
it("debounce",async () => {

  const myApi = (id) => fetch("something?id="+id)

  const myApiJestFn = jest.fn((...args) => myApi(...args));

  const myDebouncedApi = AwesomeDebouncePromise(myApiJestFn, 400);

  myDebouncedApi(1);
  myDebouncedApi(2);
  myDebouncedApi(3);

  await delay(300);
  expect(myApiJestFn).toHaveBeenCalled(0);
  await delay(400);
  expect(myApiJestFn).toHaveBeenCalled(1);
  await delay(1000);
  expect(myApiJestFn).toHaveBeenCalled(1);
})
```

This is pseudo code I just wrote. If this was helpful for your usecase I'd be happy if you submit a PR to document how this lib can be tested.

**Comment by kurt-hardy** [comment]
Thanks for your quick response. Sorry, I should have posted my component. You example is great for testing functions but with React, the functions inside the component.

It might be that I need to restructure my component, Im a little unsure.

```javascript

const searchApi = term => api.get(`search?searchTerm=${term}`);
const searchDebounce = AwesomeDebouncePromise(searchApi, 400);

export class Search extends React.Component {
    onInput = (e) => {
        searchDebounce(e.target.value)
            .then(() => {
                // do stuff
            });
    };

    render() {
        return (
            <div className="py-3 m-3">
                <span>Search</span>
                <Input
                    value={this.state.term || ""}
                    onChange={this.onInput}
                    className="mt-2"
                />
            </div>
        );
    }
}

it("should ", (done) => { 
    const wrapper = shallow(<Search {...testProps} />); 
    wrapper.find("Input").simulate("change", { target: { value: "searchTerm" } }); 
    setImmediate(() => {             
        expect(api.get).toHaveBeenCalledTimes(1); 
        done(); 
    }); 
});
```

Thanks
Kurtis

**Comment by slorber** [comment]
if you want to test that, you should inject the debounced function as prop instead, otherwise you won't be able to mock it easily

**Comment by kurt-hardy** [comment]
Ah I see, I'll do that

Thanks for your help.
