### ISSUE TITLE
Unable to return a promise? 

### ISSUE THREAD

**Issue by brymon68** [slorber/awesome-debounce-promise#13]
Hello, 

I am new to async await in general so I'm having a bit of a hard time following one of your examples. I have a button that, onClick calls a 'performHostSearch' function like:

```
  async performHostSearch(){
      this.setState({buttonLoading: true})
      const result = await this.searchAPIDebounced();
      if (result !== undefined){
        this.setState({ result })
      }
  }

  searchAPIDebounced = () =>{
    AwesomeDebouncePromise(this.searchAPI(), 500);
  } 

  async searchAPI() {
    axios.get('/api/blah?foo=${this.state.searchString}')
      .then(function (response) {
        if (response.data.records.length >0) {
          return { data: response.data.records, showResults: true, buttonText: 'Search', buttonLoading: false }
        }
      }.bind(this))
      .catch(function (error) {
        return null
      });
  }
```

Yet I am never returned a promise nor does state ever get populated with the correct result data. Any idea what I am doing wrong?

**Comment by slorber** [comment]
Hi, I'm sorry but I can't give support like that. You need to understand how promises work before using them. and your code looks like you don't really understand what you are doing with them. Take a course on promises somewhere, or copy paste from a working example if you need to ship something right nt without deep understanding.

Also this answer in the FAQ applies to your case:

![image](https://user-images.githubusercontent.com/749374/57013379-90b91700-6c0b-11e9-80f5-c2631acfd504.png)
