### ISSUE TITLE
Not debouncing, just delaying

### ISSUE THREAD

**Issue by gecko25** [slorber/awesome-debounce-promise#15]
I am trying to debounce a user search query on a text input. Exactly like the example. I think I have followed the setup instructions, but it seems like the debouncing function is not debouncing, just delaying.

```  
const searchAPI = (query) => {
    const baseUrl = absoluteUrl(null, 'localhost:3000');
    return axios.get(`${baseUrl}api/locations?location=${query}`);
  };

  const searchAPIDebounced = AwesomeDebouncePromise(searchAPI, 300);

  const handleTextChange = async (e) => {
    const keystrokes = e.target.value;
    updateLocation(keystrokes);
    const results = await searchAPIDebounced(keystrokes);
    console.log('RESULTS', results);
  };

return (
    <input
       type="text"
        onChange={handleTextChange}
    />
);

```

If increase the delay to 10000, I can clearly see that the debounce function waits awhile before it attempts to make any API calls. However, I can see in the network activity that, for a query "B-a-l-t-i-m-o-r-e", there are 9 requests being made.

I _am_ using a stateless function, and not a React class, so I am not sure if that affects anything.

**Comment by slorber** [comment]
Hi

It's hard to help if I don't see more code.

You likely recreate the denounced function everytime. Try to only create it
once. Assign it to a class property. If you use hooks you should rather use
useConstant like shawn in the exemples


Le sam. 6 juil. 2019 à 04:12, Sara Tankard <notifications@github.com> a
écrit :

**Comment by gecko25** [comment]
Okay, I was trying to have to avoid using other libraries and just using the native hook API.

**Comment by slorber** [comment]
If you use hooks, it's your responsability to understand how to store the stateful stuff inside your function component. useConstant is one solution, you could as well store that function outside the function comp (but then it will be shared across all your mounted function comps, which may not be what you want).

You could as well use a class it this looks simpler to you

https://github.com/Andarist/use-constant

It's only 5 lines of code, you can just copy that hook into your project if you don't want a new dependency:

```tsx
import * as React from 'react'

type ResultBox<T> = { v: T }

export default function useConstant<T>(fn: () => T): T {
  const ref = React.useRef<ResultBox<T>>()

  if (!ref.current) {
    ref.current = { v: fn() }
  }

  return ref.current.v
}
```

**Comment by iva3682** [comment]
@gecko25 try using the following code:

```
import useConstant from 'use-constant';
...
const searchAPIDebounced = useConstant(() => AwesomeDebouncePromise(searchAPI, 300));
...
```
