### ISSUE TITLE
Wrong package.json homepage

### ISSUE THREAD

**Issue by tkrotoff** [slorber/awesome-debounce-promise#2]
See https://github.com/slorber/awesome-debounce-promise/blob/4ab2d644b8f4dc757a0f2b7218ab19eb5b7514d9/package.json#L27

Should be https://github.com/slorber/awesome-debounce-promise

**Comment by slorber** [comment]
thanks, just noticed it too ;)

**Comment by daviddelusenet** [comment]
This version still isn't published to NPM
