### ISSUE TITLE
Get the count of debounced requests that are going to be sent

### ISSUE THREAD

**Issue by emilos** [slorber/awesome-debounce-promise#20]
I'm trying to fix some brittle specs and I'd like to implement a helper function that would let me wait until all requests finished.

It works fine if requests are being sent instantly, but when there's a debounce, I cannot rely on it anymore.

I could improve the helper fn by also checking if the count of debounced requests equals 0.

Would it make sense to expose the count of pending debounced promises by this library? I'd be happy to contribute

**Comment by slorber** [comment]
Hi,

this is a microlib so I don't want to grow its API for many usecases, rather encourage you to build your own API on top of it. 
If it's not possible, you'd rather make your own impl, because counting pending requests seems a too niche usecase to support it here

**Comment by slorber** [comment]
not sure but it. may be possible to build on top with the "onlyResolvesLast: false" option
