### ISSUE TITLE
Accessing state with debounce

### ISSUE THREAD

**Issue by bgold0** [slorber/awesome-debounce-promise#6]
Is there a way to access the state when calling debounce function?

I want to `setState({saving: true})` when the debounce function runs so the user knows when a save is happening and a `setState({saving: true})` when it is finished. I know I can do it when it finishes but I never really know when it runs because I can't access state outside of the class.

**Comment by slorber** [comment]
I see the problem.

There is a function "onlyResolvesLast" that is exported.

Didn't try this but maybe you can try doing:

```js
const save = onlyResolvesLast(saveParams => fetch(saveParams));

class SomeComp extends React.Component {
  state = {
    saving: false,
  };
 
  saveDebounced = AwesomeDebouncePromise (async () => {
    this.setState({ saving: true });
    await save();
    // onlyResolvesLast should ensure that you won't have concurrent requests trying to set saving=false
    this.setState({ saving: false });
  },500);

  onSavePress = () => {
    // optional: maybe reset to saving=false even if there is a current saving still happing in background
    this.setState({ saving: false });
    this.saveDebounced();
  }
  
}
```


Do you have in mind a better api that I could implement to support your usecase?

**Comment by bgold0** [comment]
@slorber I'm not sure where you're getting/defining `onlyResolvesLast()`. This makes sense apart from that!

**Comment by slorber** [comment]
@bgold0 I've exported the fucntion to a separate package.
 https://github.com/slorber/awesome-only-resolves-last-promise

Have you successfully achieved what you wanted?

**Comment by slorber** [comment]
Hi, 

I'm closing but feel free to reopen if you can provide more details

Also take a look at https://github.com/slorber/react-async-hook/tree/master/src
